import  com.drool.example.domain.GenericObject;

rule "FD Interest Rate for Biti Bank duration more than 1 year and below 2 years"
    when
        genObject : GenericObject( fields["bankName"]=="Citi" && fields["durationInYear"] >= 1 && fields["durationInYear"] < 2);
    then
        genObject.getResults().put("rate","3%");
end;

rule "FD Interest Rate for Biti Bank for duration more than or equal to 2 years"
    when
        genObject : GenericObject( fields["bankName"]=="Citi" && fields["durationInYear"] >= 2);
    then
        genObject.getResults().put("rate","6%");
end;

rule "FD Interest Rate for JP Bank for duration more than or equal to 1 year"
    when
        genObject : GenericObject( fields["bankName"]=="JP" && fields["durationInYear"] >= 1);
    then
       genObject.getResults().put("rate","3%");
end;

